id = 0

[router]
id = 0
max_connections = 10010
max_outgoing_packet_count = 200
max_segment_size = 104857600
max_segment_count = 10

# Standard TCP Listener (We will proxy to this)
[v4.1]
name = "v4-1"
listen = "127.0.0.1:1883" 
next_connection_delay_ms = 1
[v4.1.connections]
max_payload_size = 20480
dynamic_filters = true
connection_timeout_ms = 60000   # Increase to 2 minutes
max_inflight_count = 1000        # Allow more unacknowledged messages

[console]
listen = "0.0.0.0:3030"